image: node:latest

stages:
  - lint
  - test

test:
  stage: test
  image: node:alpine
  before_script:
    - npm i
  script:
    - npm run test-ci
  artifacts:
    untracked: false
    when: on_success
    expire_in: "30 days"
    reports:
      junit:
        - junit.xml

eslint:
  stage: lint
  script:
    - npm i
    - npm run lint

cache:
  paths:
    - node_modules/

# This is a SonarCloud check job that runs the SonarScanner.
#variables:
#  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
#  GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task

#sonarcloud-check:
#  stage: sonarcloud
#  image:
#    name: sonarsource/sonar-scanner-cli:latest
#    entrypoint: [""]
#  cache:
#    key: "${CI_JOB_NAME}"
#    paths:
#      - .sonar/cache
#  script:
#    - sonar-scanner
#  only:
#    - merge_requests
#    - main
